apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cardano-testnet-relay-deployment
  labels:
    app: relay-node
spec:
  serviceName: cardano-testnet-relay
  selector:
    matchLabels:
      app: relay-node
  template:
    metadata:
      labels:
        app: relay-node
    spec:
      containers:
        - image: inputoutput/cardano-node:latest
          name: relay-node
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: data
              mountPath: /data
          args: ["run", "--database-path", "/data", "--port", "3001"]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        # This storageClassName is used on the previously defined volume that
        # provides storage on the host machine
        storageClassName: local-storage-testnet-relay
        resources:
          requests:
            storage: 25Gi

---

apiVersion: v1
kind: Service
metadata:
  name: cardano-testnet-relay-svc
  labels:
    app: relay-node
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: relay-node
