apiVersion: v1
kind: PersistentVolume
metadata:
  name: cardano-mainnet-producer-pv-1
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce # Only allow one container to use this volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-mainnet-producer
  local:
    # Point this path to some empty directory on the NODE
    path: /home

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          # Restrict this volume to a specific Kubernetes node by hostname
          - key: kubernetes.io/hostname
            operator: Exists

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-mainnet-producer
provisioner: kubernetes.io/no-provisioner
# Docs say that local bindings should be set to WaitForFirstConsumer.
# https://kubernetes.io/docs/concepts/storage/storage-classes/#local
volumeBindingMode: WaitForFirstConsumer