apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cardano-mainnet-relay-deployment
  labels:
    app: relay-node
spec:
  serviceName: cardano-mainnet-relay
  selector:
    matchLabels:
      app: relay-node
  template:
    metadata:
      labels:
        app: relay-node
    spec:
      containers:
        - image: inputoutput/cardano-node
          name: relay-node
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: topology
              mountPath: /topology
          args: ["run", 
                 "--topology", "/topology/relay_topology.json", 
                 "--port", "3001"]
      volumes:
        - name: topology
          configMap:
            name: mainnet-relay-topology
---

apiVersion: v1
kind: Service
metadata:
  name: cardano-mainnet-relay-svc
  labels:
    app: relay-node
spec:
  ports:
  - port: 3002
    targetPort: 3001
  selector:
    app: relay-node

---

apiVersion: v1
kind: Service
metadata:
  name: cardano-mainnet-relay-svc-lb
  annotations:
    # only network load balancer supports static IP
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    # comma-separated list of Elastic IP ids
    # the length of the list must be equal to the number of subnets
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0f1fa0538892d320c
  labels:
    app: relay-node
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: relay-node
  externalTrafficPolicy: Local
  type: LoadBalancer
