apiVersion: v1
kind: PersistentVolume
metadata:
  name: cardano-testnet-relay-pv-1
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce # Only allow one container to use this volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-testnet-relay
  # # Set the path to the folder on the node that will be mounted for this volume
  local:
    path: /

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          # Restrict this volume to a specific Kubernetes node by hostname
          - key: kubernetes.io/hostname
            operator: Exists

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-testnet-relay
provisioner: kubernetes.io/no-provisioner
# Docs say that local bindings should be set to WaitForFirstConsumer.
# https://kubernetes.io/docs/concepts/storage/storage-classes/#local
volumeBindingMode: WaitForFirstConsumer