apiVersion: v1
kind: ConfigMap
metadata:
  name: mainnet-relay-topology
data:
  topology.json: |
    {
      "Producers": [
        {
          "addr": "relays-new.cardano-mainnet.iohk.io",
          "port": 3001,
          "valency": 2
        }
      ]
    }